/**
 * AV Media Telangana - Timeline Event Model
 * Standardized timeline event object generated by the Playlist Interpreter.
 */

export const EVENT_TYPES = Object.freeze({
  BADGE_IN: 'BADGE_IN',
  BADGE_HOLD: 'BADGE_HOLD',
  NEWS_START: 'NEWS_START',
  LOGO_SEPARATOR: 'LOGO_SEPARATOR',
  NEWS_END: 'NEWS_END',
  BADGE_OUT: 'BADGE_OUT',
  PLAYLIST_END: 'PLAYLIST_END'
});

export class TimelineEvent {
  constructor({
    type,
    playlistId = null,
    label = '',
    theme = 'district',
    newsIndex = -1,
    payload = {},
    timestamp = Date.now()
  } = {}) {
    if (!Object.values(EVENT_TYPES).includes(type)) {
      throw new Error(`[TimelineEvent] Invalid event type specified: "${type}"`);
    }

    this.type = type;
    this.playlistId = playlistId;
    this.label = String(label).trim();
    this.theme = String(theme).toLowerCase().trim() || 'district';
    this.newsIndex = typeof newsIndex === 'number' ? newsIndex : -1;
    this.payload = payload && typeof payload === 'object' ? payload : {};
    this.timestamp = typeof timestamp === 'number' ? timestamp : Date.now();
  }
}
